export enum InventoryMovementType {
  ENTRY = 'ENTRY',
  SALE = 'SALE',
  RESERVATION = 'RESERVATION',
  RESERVATION_RELEASE = 'RESERVATION_RELEASE',
  RETURN = 'RETURN',
  ADJUSTMENT = 'ADJUSTMENT',
  PENDING_ENTRY = 'PENDING_ENTRY',
  CHECKOUT_HOLD = 'CHECKOUT_HOLD',
  CHECKOUT_RELEASE = 'CHECKOUT_RELEASE',
}

export enum InventoryMovementStatus {
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}
