import type { Turno } from '../src/services/turnos.service';
export const turno: Turno = {
  id: 1,
  registerId: 1,
  branchId: 2,
  registerName: 'Caja 1',
  branchName: 'Centro',
  userId: 12,
  cashier: 'Cajero',
  openedAt: '2026-09-12T14:00:00Z',
  closedAt: null,
  currency: 'BOB',
  openingCash: 100,
  cashTotal: 160,
  cardTotal: 80,
  qrTotal: 20,
  transferTotal: 40,
  totalSales: 300,
  saleCount: 4,
  expectedCash: 260,
  countedCash: null,
  difference: null,
  closingNote: null,
};
