/** Claves de cache de TanStack Query en un solo lugar para invalidar sin adivinar. */
export const claves = {
  productos: (filtros?: unknown) => ['productos', filtros ?? {}] as const,
  producto: (id: number) => ['producto', id] as const,
  recursosRA: (id: number) => ['recursos-ra', id] as const,
  categorias: ['categorias'] as const,
  tallas: ['tallas'] as const,
  colores: ['colores'] as const,
  temporadas: ['temporadas'] as const,
  colecciones: ['colecciones'] as const,
  sucursales: ['sucursales'] as const,
  proveedores: ['proveedores'] as const,
  productosProveedor: (id: number) => ['proveedor-productos', id] as const,
  usuarios: (filtros?: unknown) => ['usuarios', filtros ?? {}] as const,
  roles: ['roles'] as const,
  empleados: (idSucursal?: number) => ['empleados', idSucursal ?? null] as const,
  inventario: (filtros?: unknown) => ['inventario', filtros ?? {}] as const,
  disponibilidad: (consulta: unknown) => ['disponibilidad', consulta] as const,
  movimientos: (filtros?: unknown) => ['movimientos', filtros ?? {}] as const,
  carrito: ['carrito'] as const,
  reservas: (filtros?: unknown) => ['reservas', filtros ?? {}] as const,
  reserva: (id: number) => ['reserva', id] as const,
  ventas: (filtros?: unknown) => ['ventas', filtros ?? {}] as const,
  venta: (id: number) => ['venta', id] as const,
  reportes: (nombre: string, filtros?: unknown) => ['reportes', nombre, filtros ?? {}] as const,
  recomendaciones: (opciones?: unknown) => ['recomendaciones', opciones ?? {}] as const,
};
